config/routes.rb
Rails.application.routes.draw do
   
 
  
  resources :videos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }
  #as :user do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   #get 'sign_in' => 'users/sessions#new', :as => "sign_in"
   #get 'sign_up' => 'users/registrations#new', :as => "sign_up"  
   #get 'sign_out' => 'users/sessions#destroy', :as => "sign_out" 
   get 'home/index'
   root 'home#index' 
   root to: "photos#index"
   root "videos#index"
   resources :photos
end

app/models/video.rb
class Video < ApplicationRecord
	has_attached_file :attachment, styles: {
    medium: {geometry: "640x480", format:'mp4'},
    thumb: {geometry: "100x100#", format:'jpg', time: 10}
    }, processors: [:transcoder]

  validates_attachment_content_type :attachment, content_type: /\Avideo\/.*\Z/
  validates_attachment :attachment, size: {less_than: 130.megabytes}	
end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base

  private

    def video_params
      params.require(:video).permit(:title, :description, :attachment)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<section id="signin" class="full-height cl-pd-tp-60 ng-scope">
  <div>
    <%= form_with(model: video, local: true) do |form| %>
      <div class="register-box">
      <div class="register-box-body">
        <h1 class="text-center">Upload new video</h1>
        <%= content_tag(:div, flash[:error], :id => "flash_error", :class => "alert alert-danger") if flash[:error] %>
        <%= content_tag(:div, flash[:notice], :id => "flash_notice", :class => "alert alert-info") if flash[:notice] %>
        <%= content_tag(:div, flash[:alert], :id => "flash_alert", :class => "alert alert-warning") if flash[:alert] %>
      
         <p class="login-box-msg"><!-- Login Now.. --></p>
          <% if video.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>
                <ul>
                  <% video.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
            </div>
          <% end %>

          <div class="form-group has-feedback">
            <div class="field">
              <%= form.text_field :title, id: :video_title, placeholder: "Title", autofocus: true, :class => "form-control border-radius-none" %>
            </div>
          </div>

          <div class="form-group has-feedback">
            <div class="field">
              <%= form.text_area :description, id: :video_description, autofocus: true, placeholder: "Description", :class => "form-control border-radius-none" %>
            </div>
          </div>

          <div class="form-group has-feedback">
            <div class="field">
              <%= form.file_field :attachment %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12 col-md-4">
              <%= form.submit "Upload Video", class: "btn btn-success btn-b btn-flat" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/videos/edit.html.erb
<h1 class="text-center">Editing Video</h1>
<%= render 'form', video: @video %>

app/views/videos/index.html.erb
<section id="signin" class="full-height cl-pd-tp-60 ng-scope">
<div>
 <div class="register-box" style="width:100%">
      <div class="register-box-body">
        <h1 class="text-center">Videos</h1>
<br>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td>
        <%= link_to 'Show', video %> |
        <%= link_to 'Edit', edit_video_path(video) %> |
        <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>
</section>

app/views/videos/new.html.erb
<%= render 'form', video: @video %>

<!--%= link_to 'Back', videos_path %>-->

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Video:</strong>
  <%= video_tag @video.attachment.url,
    controls: true, style: "max-width: 100%;" %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>