config/routes.rb
Rails.application.routes.draw do
   
 
  
  resources :videos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }
  #as :user do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   #get 'sign_in' => 'users/sessions#new', :as => "sign_in"
   #get 'sign_up' => 'users/registrations#new', :as => "sign_up"  
   #get 'sign_out' => 'users/sessions#destroy', :as => "sign_out" 
   get 'home/index'
   root 'home#index' 
   root to: "photos#index"
   root "videos#index"
   resources :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
	 has_attached_file :image
	 validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	# do_not_validate_attachment_file_type :image

	 #validates_attachment :image, presence: true,
                          # content_type: { content_type: "image/jpeg" },
                           #size: { in: 0..10.kilobytes }

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
		@photos = Photo.order('created_at')
	end

	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new(photo_params)
		if @photo.save
			flash[:notice] = "Successfully added new photo!"
		    redirect_to root_path
        else
			flash[:alert] = "Error adding new photo!"
   			render :new
        end
	end

	def destroy
		@photo = Photo.find(params[:id])
          if @photo.destroy
             flash[:notice] = "Successfully deleted photo!"
             redirect_to root_path
          else
             flash[:alert] = "Error deleting photo!"
          end
	end

	  private

	  #Permitted parameters when creating a photo. This is used for security reasons.
	  def photo_params
	  	params.require(:photo).permit(:title, :image)
	  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/index.html.erb
<div class="center-block text-center">
<h1>Photo</h1>
</div>

<div class="masonry">
      <% @photos.each do |photo| %>
      <div class="item">
      <!-- Renders image -->
      <%= link_to image_tag(photo.image.url, class: 'photoitem'), photo.image.url, target: '_blank' %>
      <div class="center-block text-center">
        <h4><%= photo.title %></h4>
      
      <%= link_to 'Remove', photo_path(photo), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
      </div>
      </div>
      <% end %>
</div>

app/views/photos/new.html.erb
<section id="signin" class="full-height cl-pd-tp-60 ng-scope">
  <div>
    <%= form_for @photo, html: { multipart: true} do |f| %>
      <div class="register-box">
        <div class="register-box-body">
          <h1 class="text-center">Upload new image</h1>
          <%= content_tag(:div, flash[:error], :id => "flash_error", :class => "alert alert-danger") if flash[:error] %>
          <%= content_tag(:div, flash[:notice], :id => "flash_notice", :class => "alert alert-info") if flash[:notice] %>
          <%= content_tag(:div, flash[:alert], :id => "flash_alert", :class => "alert alert-warning") if flash[:alert] %>
      
            <p class="login-box-msg"><!-- Login Now.. --></p>
	           <% if @photo.errors.any? %>
	             <div id="error_explanation">
		            <h2>
			           <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
		            </h2>
		            <ul>
			           <% @photo.errors.full_messages.each do |msg| %>	
                  <li>
			  	          <%= msg %>
                  </li>
                 <% end %>
		            </ul>
	             </div>
             <% end %>
          
             <div class="form-group has-feedback">
              <div class="field">
                 <%= f.text_field :title, autofocus: true, placeholder: "Title", :class => "form-control border-radius-none" %>
              </div>
             </div>

             <div class="form-group has-feedback">
              <div class="field">
                 <%= f.file_field :image %>
              </div>
             </div>

             <div class="row">
              <div class="col-md-12 col-md-4">
  	           <%= f.submit "Upload Photo", class: "btn btn-success btn-b btn-flat" %>
              </div>
             </div>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</section>
        

           
              